// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using demoApp0818.Data;

#nullable disable

namespace demoApp0818.Migrations
{
    [DbContext(typeof(BookDBContext))]
    partial class BookDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("demoApp0818.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            CoverImageUrl = "https://example.com/alchemist.jpg",
                            Description = "A journey of self-discovery and dreams.",
                            Price = 15.99m,
                            Stock = 10,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "George Orwell",
                            Category = "Dystopian",
                            CoverImageUrl = "https://example.com/1984.jpg",
                            Description = "A dystopian novel about surveillance and control.",
                            Price = 12.50m,
                            Stock = 15,
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Harper Lee",
                            Category = "Classic",
                            CoverImageUrl = "https://example.com/mockingbird.jpg",
                            Description = "A novel of racial injustice and childhood innocence.",
                            Price = 18.00m,
                            Stock = 20,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "F. Scott Fitzgerald",
                            Category = "Classic",
                            CoverImageUrl = "https://example.com/gatsby.jpg",
                            Description = "A story of wealth, love, and the American Dream.",
                            Price = 14.99m,
                            Stock = 8,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Jane Austen",
                            Category = "Romance",
                            CoverImageUrl = "https://example.com/pride.jpg",
                            Description = "Romantic novel of manners in 19th century England.",
                            Price = 11.50m,
                            Stock = 12,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Herman Melville",
                            Category = "Adventure",
                            CoverImageUrl = "https://example.com/mobydick.jpg",
                            Description = "A tale of obsession and revenge against a whale.",
                            Price = 16.75m,
                            Stock = 5,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "J.R.R. Tolkien",
                            Category = "Fantasy",
                            CoverImageUrl = "https://example.com/hobbit.jpg",
                            Description = "The prelude to the Lord of the Rings saga.",
                            Price = 19.99m,
                            Stock = 25,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Aldous Huxley",
                            Category = "Dystopian",
                            CoverImageUrl = "https://example.com/bravenewworld.jpg",
                            Description = "A futuristic vision of a controlled society.",
                            Price = 13.40m,
                            Stock = 9,
                            Title = "Brave New World"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Fyodor Dostoevsky",
                            Category = "Classic",
                            CoverImageUrl = "https://example.com/crime.jpg",
                            Description = "A psychological study of guilt and redemption.",
                            Price = 17.25m,
                            Stock = 7,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "J.D. Salinger",
                            Category = "Classic",
                            CoverImageUrl = "https://example.com/catcher.jpg",
                            Description = "A coming-of-age story about teenage alienation.",
                            Price = 10.99m,
                            Stock = 14,
                            Title = "The Catcher in the Rye"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
